# wrangler.toml

# 你的 Pages 项目名称，必须和 Cloudflare 上的完全一致
name = "r2-proxy-alias1"
# 兼容性日期，使用一个最近的日期即可
compatibility_date = "2023-11-21"

pages_build_output_dir = "dist"

# [[r2_buckets]] 就是 R2 绑定的配置
[[r2_buckets]]
# binding = "变量名"，必须和代码 context.env.PROXY_BUCKET 一致
binding = "PROXY_BUCKET"
# bucket_name = "你的 R2 存储桶的真实名称"
bucket_name = "alias1"

# [vars] 就是环境变量的配置
[vars]
MAX_AGE = "31536000"
R2_CUSTOM_DOMAIN = "cache.alias1.de5.net"

